#!/bin/bash

set -e

echo "=========================================="
echo " RatioForge Render Container"
echo "=========================================="

echo "Starting virtual display..."

Xvfb :99 -screen 0 1280x720x24 \
    -ac \
    +extension GLX \
    +render \
    -noreset \
    >/tmp/xvfb.log 2>&1 &

XVFB_PID=$!

echo "Xvfb started: $XVFB_PID"

sleep 2

echo ""
echo "Wine version:"
wine --version || true

echo ""
echo "Initializing Wine..."

wineboot --init >/tmp/wineboot.log 2>&1 || true

sleep 3

echo ""
echo "Checking RatioForge files..."

ls -lah /app/RatioForge

echo ""
echo "Starting RatioForge..."

# Find the main executable generated by dotnet publish.
RATIOFORGE_EXE=$(find /app/RatioForge -maxdepth 1 -type f -iname "RatioForge.exe" | head -n 1)

if [ -z "$RATIOFORGE_EXE" ]; then
    echo "ERROR: RatioForge.exe was not found!"
    echo "Files available:"
    find /app/RatioForge -maxdepth 2 -type f
    exit 1
fi

echo "Found:"
echo "$RATIOFORGE_EXE"

# Launch RatioForge through Wine.
wine "$RATIOFORGE_EXE" \
    >/tmp/ratioforge.log 2>&1 &

RATIOFORGE_PID=$!

echo ""
echo "RatioForge PID: $RATIOFORGE_PID"

echo ""
echo "=========================================="
echo " Starting Render health server"
echo "=========================================="

# Simple HTTP server.
python3 - <<'PY'
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

PORT = int(os.environ.get("PORT", "10000"))


class Handler(BaseHTTPRequestHandler):

    def do_GET(self):

        if self.path == "/":
            body = b"RatioForge container is running\n"
            status = 200

        elif self.path == "/health":
            body = b'{"status":"ok"}\n'
            status = 200

        else:
            body = b"Not found\n"
            status = 404

        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()

        self.wfile.write(body)

    def log_message(self, format, *args):
        print("[HTTP]", format % args)


server = HTTPServer(("0.0.0.0", PORT), Handler)

print(f"HTTP server listening on 0.0.0.0:{PORT}")

server.serve_forever()
PY
