#!/bin/bash

set -e

echo "=============================================="
echo " RatioForge - Docker/Wine"
echo "=============================================="

echo ""
echo "[1/6] Starting virtual display..."

Xvfb :99 \
    -screen 0 1280x720x24 \
    -ac \
    +extension GLX \
    +render \
    -noreset \
    >/tmp/xvfb.log 2>&1 &

XVFB_PID=$!

sleep 3

if ! kill -0 "$XVFB_PID" 2>/dev/null; then
    echo "ERROR: Xvfb failed to start."
    cat /tmp/xvfb.log || true
    exit 1
fi

echo "Xvfb running with PID: $XVFB_PID"


echo ""
echo "[2/6] Checking Wine..."

wine --version || true


echo ""
echo "[3/6] Initializing Wine..."

wineboot --init >/tmp/wineboot.log 2>&1 || true

sleep 5

echo "Wine initialized."


echo ""
echo "[4/6] Checking RatioForge..."

echo "Contents of /app/RatioForge:"
ls -lah /app/RatioForge


RATIOFORGE_EXE="/app/RatioForge/RatioForge.exe"

if [ ! -f "$RATIOFORGE_EXE" ]; then

    echo ""
    echo "ERROR: RatioForge.exe was not found!"
    echo ""

    echo "Files generated by dotnet publish:"
    find /app/RatioForge -maxdepth 2 -type f -print

    echo ""
    echo "Wine log:"
    cat /tmp/wineboot.log || true

    exit 1
fi


echo ""
echo "Found RatioForge:"
echo "$RATIOFORGE_EXE"


echo ""
echo "[5/6] Starting RatioForge..."

wine "$RATIOFORGE_EXE" \
    >/tmp/ratioforge.log 2>&1 &

RATIOFORGE_PID=$!

sleep 5

echo ""
echo "RatioForge PID: $RATIOFORGE_PID"


echo ""
echo "=============================================="
echo " RatioForge output"
echo "=============================================="

if kill -0 "$RATIOFORGE_PID" 2>/dev/null; then
    echo "RatioForge process is running."
else
    echo "WARNING: RatioForge exited."
    echo ""
    echo "RatioForge log:"
    cat /tmp/ratioforge.log || true
fi


echo ""
echo "[6/6] Starting Render HTTP health server..."

python3 - <<'PY'
import os
from http.server import BaseHTTPRequestHandler
from http.server import HTTPServer

PORT = int(os.environ.get("PORT", "10000"))


class Handler(BaseHTTPRequestHandler):

    def do_GET(self):

        if self.path == "/":
            body = b"RatioForge container is running\n"
            status = 200

        elif self.path == "/health":
            body = b'{"status":"ok"}\n'
            status = 200

        elif self.path == "/status":

            ratioforge_running = False

            try:
                with open("/tmp/ratioforge.pid", "r") as f:
                    pid = int(f.read().strip())

                os.kill(pid, 0)
                ratioforge_running = True

            except Exception:
                ratioforge_running = False

            if ratioforge_running:
                body = b'{"status":"ok","ratioforge":"running"}\n'
            else:
                body = b'{"status":"ok","ratioforge":"stopped"}\n'

            status = 200

        else:
            body = b'{"error":"not found"}\n'
            status = 404

        self.send_response(status)

        self.send_header(
            "Content-Type",
            "application/json"
        )

        self.send_header(
            "Content-Length",
            str(len(body))
        )

        self.end_headers()

        self.wfile.write(body)

    def log_message(self, format, *args):
        print("[HTTP]", format % args)


with open("/tmp/ratioforge.pid", "w") as f:
    f.write(os.environ.get("RATIOFORGE_PID", ""))


server = HTTPServer(
    ("0.0.0.0", PORT),
    Handler
)

print(
    f"HTTP server listening on "
    f"0.0.0.0:{PORT}",
    flush=True
)

server.serve_forever()
PY
